# Generated by Django 4.2.5 on 2023-09-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0002_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='isbn',
        ),
    ]
