# Generated by Django 4.2.5 on 2023-09-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0003_rename_titulo_produto_nome_remove_produto_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='temas', to='fabidecor.categoria'),
            preserve_default=False,
        ),
    ]
