# Generated by Django 4.2.5 on 2023-09-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0004_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fabidecor.tema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fabidecor.categoria'),
        ),
    ]
