# Generated by Django 4.2.5 on 2023-09-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0005_produto_tema_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temas', to='fabidecor.tema'),
        ),
    ]
